dist: bionic
matrix:
  include:
    - language: python
      python: 3.7
    - language: cpp
compiler:
  - clang
  - gcc
os:
  - linux
before_install:
  - python --version
  - python -m pip install -r requirements.txt
install:
  - .venv/bin/cmake --version
  - .venv/bin/cmake . -G Ninja -DCMAKE_BUILD_TYPE=Release
  - .venv/bin/cmake --build . --target all