language: cpp
dist: bionic
python:
  - "3.7"
compiler:
  - clang
  - gcc
os:
  - linux
install:
  - python -m pip install -r requirements.txt
  - .venv/bin/cmake --version
  - .venv/bin/cmake . -G Ninja -DCMAKE_BUILD_TYPE=Release
  - .venv/bin/cmake --build . --target all