dist: bionic
language: cpp
compiler:
  - clang
  - gcc
os:
  - linux
before_install:
  - pyenv install 3.7.1 --skip-existing
  - pyenv local 3.7.1
  - python -m venv cpp-template-venv
  - pyenv local cpp-template-venv
  - pip install -r requirements.txt
install:
  - cmake --version
  - cmake . -G Ninja -DCMAKE_BUILD_TYPE=Release
  - cmake --build . --target all
script:
  - bin/test